
name: CI Pipeline


on:
  push:
    branches: [ main ]  
  pull_request: 
    branches: [ main ] 

jobs:
  test:
    runs-on: ubuntu-latest 
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3  

      - name: Set up .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' 

      - name: Build project
        run: dotnet build UnitTestProject1\UnitTestProject1.csproj --configuration Release 

      - name: Run unit tests
        run: dotnet test UnitTestProject1\UnitTestProject1.csproj --no-build --logger trx 
